version: '3.4'

services:
  catsshelter.service:
    image: ${DOCKER_REGISTRY-}catsshelterservice
    build:
      context: ./src
      dockerfile: CatsShelter.Service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "27018:27017"