version: '3.4'

services:
  catsshelter.service:
    image: ${DOCKER_REGISTRY-}catsshelterservice
    build:
      context: ./src
      dockerfile: CatsShelter.Service/Dockerfile
    env_file:
      - .env
    ports:
      - "51217:80"
      - "44349:443"
    volumes:
      - ${HOME}/.aspnet/https:/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets      
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "27018:27017"