version: '3.4'

services:
  catsshelter.service:
    image: ${DOCKER_REGISTRY-}catsshelterservice
    build:
      context: .
      dockerfile: src/CatsShelter.Service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    env_file:
      - .env
volumes:
  mongodb_data_container: